# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VerilogProject/RISCV/sources/ip/insmem/insmem.xci
# IP: The module: 'insmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VerilogProject/RISCV/sources/ip/insmem/insmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/VerilogProject/RISCV/sources/ip/insmem/insmem.xci
# IP: The module: 'insmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VerilogProject/RISCV/sources/ip/insmem/insmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
