# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/VerilogProject/RISCV/fpgaol.xdc

# IP: D:/VerilogProject/RISCV/sources/ip/datamem/datamem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datamem || ORIG_REF_NAME==datamem} -quiet] -quiet
